version: '3.5'
services:
  parsedmarc:
    build: ./parsedmarc/
    volumes:
      - ./files:/input:ro
      - ./output_files:/output
    command: parsedmarc -c /parsedmarc.ini /input/* --debug
    depends_on:
      - opensearch
    restart: on-failure

  opensearch:
    image: opensearchproject/opensearch:2.11.1
    environment:
      - discovery.type=single-node
    volumes:
      - ./opensearch_data:/usr/share/opensearch/data

  grafana:
    build: ./grafana/
    ports:
      - "3000:3000"
    user: root
    environment:
      GF_INSTALL_PLUGINS: grafana-piechart-panel,grafana-worldmap-panel,grafana-opensearch-datasource
      GF_AUTH_ANONYMOUS_ENABLED: 'true'
