apiVersion: 1

datasources:
- name: 'dmarc-ag'
  type: 'grafana-opensearch-datasource'
  access: 'proxy'
  orgId: 1
  url: 'https://opensearch:9200'
  basicAuth: true
  basicAuthUser: admin
  jsonData:
    database: '[dmarc_aggregate-]YYYY-MM-DD'
    flavor: 'opensearch'
    interval: 'Daily'
    timeField: 'date_range'
    tlsSkipVerify: true
    version: '2.11.1'
  secureJsonData:
    basicAuthPassword: admin
  version: 1
- name: 'dmarc-fo'
  type: 'grafana-opensearch-datasource'
  access: 'proxy'
  orgId: 1
  url: 'https://opensearch:9200'
  basicAuth: true
  basicAuthUser: admin
  jsonData:
    database: '[dmarc_forensic-]YYYY-MM-DD'
    flavor: 'opensearch'
    interval: 'Daily'
    timeField: 'arrival_date'
    tlsSkipVerify: true
    version: '2.11.1'
  secureJsonData:
    basicAuthPassword: admin
  version: 1

